### ISSUE TITLE
Release version 1.3.14

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#1392]
- [x] Add latest translations from Transifex
- [x] Test building of binary tarballs: `./autobuild/synfigstudio-release.sh`
- [x] Add release commit and tag: `./version-release.sh`
- [x] Build binaries
- [x] Write release notes + announcement text for blog post
- [x] Upload binaries to GitHub, FossHub, Sf.net, Paddle
- [x] Publish announcement on website
- [x] Send announcement to subscribers in email list
- [x] Notify affected people in support tickets
- [x] Notify contributors who did Arabic translation: https://github.com/synfig/synfig/issues/1198 and [forums](https://forums.synfig.org/t/looking-for-arabic-translation-for-synfig-ui/10704)
- [x] Post update to https://github.com/synfig/synfig/issues/314
- [x] Update configuration for TimeLoop layer in synfig-tests - #1327

**Comment by morevnaproject** [comment]
Binaries building done.

**Comment by rodolforg** [comment]
Some help for release notes in branch 1.3.x:

Bugfixes
---

Fixed crash when removing a Spline vertex using "Remove item (Smart)" (fix #1188)

Fixed incorrect placement of vertex on bline in 1.3.13 (fix #1289 and #1290)

Fixed crash with Layer_Shade without sublayers (fix #1272)

Fixed some memory leaks

Fixed popup menu popping down right after button release for Widget Gradient/Spline (fix #1277)

Fixed hang when opening a second .sif file from Explorer (Windows) (fix #291)

Fixed "local time" of Time Loop layer (fix #479)

Fixed "Render Progress" percentage when exporting a subset of frames (fix #1304)

Fixed crash when undoing layer deletion (fix #1070)

Fixed TimeTrack not updating when new waypoints added to bone (fix #1342)

Fixed importing of 16-bit PNG files (fix #1160 and #1371)

Improvement
---

Show interpolation type directly in waypoint's context menu

Added vectorizer feature credits to about dialog


???
---
Cleanup unwanted console messages

Updated translations 2020-04-24

OSX build: Remove hardcoded references to Python version

**Comment by morevnaproject** [comment]
Oh, thank you so much for help with that! :tada:

**Comment by morevnaproject** [comment]
@rodolforg I have added those release notes to Synfig Docs, so they can be easily editable by anyone now - https://synfig.readthedocs.io/en/latest/releases/development/1.3.14.html (I have slightly cleaned it up, removing the changes that are probably not in scope of user interest).

https://github.com/synfig/synfig-docs/commit/41fe1a93e161aac4e81bd84f05b5bade676975ab

P.S. I have uploaded all packages and [published the announcement](https://www.synfig.org/2020/05/07/synfig-studio-1-3-14-released/). Thank you so much for your help! ^__^

**Comment by morevnaproject** [comment]
Completed! Congratulations with the release! :tada:
