### ISSUE TITLE
Build system roadmap (near future, 2020)

### ISSUE THREAD

**Issue by ice0** [synfig/synfig#1660]
#### MacOS
- [ ] Check librsvg hack on 10.10 (and eliminate it if possible)
- [ ]  Fix ImageMagick/libtool problem, contact with libtool authors

#### MSYS2
- [ ] Remove `set_env.sh` script, use builtin environment variables
- [ ] Update MSYS2 MLT to v6.22.1, and add `avformat` support
- [ ] Switch to MSYS2 MLT and remove custom MLT build script
- [ ] Fix CMake to use MSYS2 MLT (it now uses hardcoded paths)
- [ ] Add description and icon integration to autotools script

#### Windows/MSVC
- [ ] Move changes required to Synfig build to patch
- [ ] Add new CI pipeline (AZP or github)

#### Flatpak
- [ ] Fix synfig_icon.png generation, and remove hack with name replacing

#### Appveyor
- [ ] Check why 32 is builds faster when 64-bit
